### ISSUE TITLE
Simple Components for LCA Calculations

### ISSUE THREAD

**Issue by moethu** [moethu/Tortuga#2]
In order to meet the Leed requirements we got to implement surface based components (as we already got it in the material editor) and foundations (tbi):

![2015-05-29_13h02_40](https://cloud.githubusercontent.com/assets/8201465/7882724/70d04584-0608-11e5-8ad5-aba36c09d180.png)

**Comment by moethu** [comment]
Components for Volumes, Surfaces, Beams and Foundation added

![2015-06-01_16h53_49](https://cloud.githubusercontent.com/assets/8201465/7917014/320f708a-087f-11e5-9882-de686d370bd4.png)

**Comment by mostaphaRoudsari** [comment]
@moethu I like the components that let users automate creating geometries but at the same time I think it might be better to break down the geometry creation from the calculation. Let's say I have a structure different than your default geometry creator. What would be the best approach in that case?

**Comment by moethu** [comment]
Good point, well this one is just to cover the LEED requirements for foundations. I've never seen anyone modelling foundations at such an early stage - so this one just gives you the optiona to add an easy foundation. In any other case you're using the standard components: linear (for beams etc), surface and volume calculator. They can be used with any kind of brep or surface.
Does that make sense?

**Comment by mostaphaRoudsari** [comment]
Make total sense. Thank you for the clarification.
